# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: theme.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='theme.proto',
  package='theme',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0btheme.proto\x12\x05theme\"\x8b\x01\n\x05theme\x12\x10\n\x08\x63olorOne\x18\x01 \x01(\t\x12\x10\n\x08\x63olorTwo\x18\x02 \x01(\t\x12\x12\n\ncolorThree\x18\x03 \x01(\t\x12\x11\n\tcolorFour\x18\x04 \x01(\t\x12\x11\n\tcolorFive\x18\x05 \x01(\t\x12\x10\n\x08\x63olorSix\x18\x06 \x01(\t\x12\x12\n\ncolorSeven\x18\x07 \x01(\tb\x06proto3')
)




_THEME = _descriptor.Descriptor(
  name='theme',
  full_name='theme.theme',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='colorOne', full_name='theme.theme.colorOne', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='colorTwo', full_name='theme.theme.colorTwo', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='colorThree', full_name='theme.theme.colorThree', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='colorFour', full_name='theme.theme.colorFour', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='colorFive', full_name='theme.theme.colorFive', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='colorSix', full_name='theme.theme.colorSix', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='colorSeven', full_name='theme.theme.colorSeven', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=162,
)

DESCRIPTOR.message_types_by_name['theme'] = _THEME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

theme = _reflection.GeneratedProtocolMessageType('theme', (_message.Message,), dict(
  DESCRIPTOR = _THEME,
  __module__ = 'theme_pb2'
  # @@protoc_insertion_point(class_scope:theme.theme)
  ))
_sym_db.RegisterMessage(theme)


# @@protoc_insertion_point(module_scope)
