# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eeg_payload.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='eeg_payload.proto',
  package='theme',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11\x65\x65g_payload.proto\x12\x05theme\"\x97\x03\n\x05theme\x12\x17\n\x0fmeanAlphaTpNine\x18\x01 \x01(\x02\x12\x16\n\x0emeanBetaTpNine\x18\x02 \x01(\x02\x12\x17\n\x0fmeanThetaTpNine\x18\x03 \x01(\x02\x12\x17\n\x0fmeanDeltaTpNine\x18\x04 \x01(\x02\x12\x16\n\x0emeanAlphaTpTen\x18\x05 \x01(\x02\x12\x15\n\rmeanBetaTpTen\x18\x06 \x01(\x02\x12\x16\n\x0emeanThetaTpTen\x18\x07 \x01(\x02\x12\x16\n\x0emeanDeltaTpTen\x18\x08 \x01(\x02\x12\x18\n\x10meanAlphaAfSeven\x18\n \x01(\x02\x12\x17\n\x0fmeanBetaAfSeven\x18\x0b \x01(\x02\x12\x18\n\x10meanThetaAfSeven\x18\x0c \x01(\x02\x12\x18\n\x10meanDeltaAfSeven\x18\r \x01(\x02\x12\x18\n\x10meanAlphaAfEight\x18\x0e \x01(\x02\x12\x17\n\x0fmeanBetaAfEight\x18\x0f \x01(\x02\x12\x18\n\x10meanThetaAfEight\x18\x10 \x01(\x02\x12\x18\n\x10meanDeltaAfEight\x18\x11 \x01(\x02\x62\x06proto3')
)




_THEME = _descriptor.Descriptor(
  name='theme',
  full_name='theme.theme',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='meanAlphaTpNine', full_name='theme.theme.meanAlphaTpNine', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='meanBetaTpNine', full_name='theme.theme.meanBetaTpNine', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='meanThetaTpNine', full_name='theme.theme.meanThetaTpNine', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='meanDeltaTpNine', full_name='theme.theme.meanDeltaTpNine', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='meanAlphaTpTen', full_name='theme.theme.meanAlphaTpTen', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='meanBetaTpTen', full_name='theme.theme.meanBetaTpTen', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='meanThetaTpTen', full_name='theme.theme.meanThetaTpTen', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='meanDeltaTpTen', full_name='theme.theme.meanDeltaTpTen', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='meanAlphaAfSeven', full_name='theme.theme.meanAlphaAfSeven', index=8,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='meanBetaAfSeven', full_name='theme.theme.meanBetaAfSeven', index=9,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='meanThetaAfSeven', full_name='theme.theme.meanThetaAfSeven', index=10,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='meanDeltaAfSeven', full_name='theme.theme.meanDeltaAfSeven', index=11,
      number=13, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='meanAlphaAfEight', full_name='theme.theme.meanAlphaAfEight', index=12,
      number=14, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='meanBetaAfEight', full_name='theme.theme.meanBetaAfEight', index=13,
      number=15, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='meanThetaAfEight', full_name='theme.theme.meanThetaAfEight', index=14,
      number=16, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='meanDeltaAfEight', full_name='theme.theme.meanDeltaAfEight', index=15,
      number=17, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=436,
)

DESCRIPTOR.message_types_by_name['theme'] = _THEME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

theme = _reflection.GeneratedProtocolMessageType('theme', (_message.Message,), dict(
  DESCRIPTOR = _THEME,
  __module__ = 'eeg_payload_pb2'
  # @@protoc_insertion_point(class_scope:theme.theme)
  ))
_sym_db.RegisterMessage(theme)


# @@protoc_insertion_point(module_scope)
